spring.application.name=gateway-mvc-openapi
springdoc.cache.disabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
scalar.enabled=true
#scalar.path=/

spring.mvc.apiversion.default=1.0.0
spring.mvc.apiversion.required=false
spring.mvc.apiversion.use.header=X-API-Version
logging.level.org.springframework.cloud.gateway.server.mvc=TRACE
logging.level.org.springframework.web=TRACE
management.endpoints.web.exposure.include=*

spring.cloud.discovery.client.simple.instances.httpbin[0].service-id=httpbin
spring.cloud.discovery.client.simple.instances.httpbin[0].instance-id=httpbin-0
spring.cloud.discovery.client.simple.instances.httpbin[0].host=localhost
spring.cloud.discovery.client.simple.instances.httpbin[0].port=8080
spring.cloud.discovery.client.simple.instances.httpbin[0].metadata.response-ref-path=/httpbin-spec.json#/paths/~1anything~1{anything}