spring.application.name=gateway-mvc-openapi
springdoc.cache.disabled=true
springdoc.api-docs.enabled=true
scalar.enabled=true
scalar.path=/

spring.mvc.apiversion.default=1.0.0
spring.mvc.apiversion.required=false
spring.mvc.apiversion.use.header=X-API-Version
logging.level.org.springframework.cloud.gateway.server.mvc=TRACE
logging.level.org.springframework.web=TRACE
management.endpoints.web.exposure.include=*
