spring.application.name=gateway-mvc-openapi
springdoc.cache.disabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
scalar.enabled=true
#scalar.path=/

spring.mvc.apiversion.default=1.0.0
spring.mvc.apiversion.required=false
spring.mvc.apiversion.use.header=X-API-Version
logging.level.org.springframework.cloud.gateway.server.mvc=TRACE
logging.level.org.springframework.web=TRACE
management.endpoints.web.exposure.include=*

spring.cloud.discovery.client.simple.instances.users[0].service-id=users
spring.cloud.discovery.client.simple.instances.users[0].instance-id=users-0
spring.cloud.discovery.client.simple.instances.users[0].host=localhost
spring.cloud.discovery.client.simple.instances.users[0].port=9090
spring.cloud.discovery.client.simple.instances.users[0].metadata.response-ref-path=/userdocs#